places = ["B","A","F","C","E","D"]
print(places)
print(sorted(places))
print(sorted(places,reverse=True))
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse= True)
print(places)

rivers = []
print(len(rivers))
rivers.append("Kaveri")
rivers.insert(1,"periyar")
rivers.append("Kallada")
print(rivers)
rivers[2] = "Bharathappuzha"
del rivers[0]
rivers.pop()
rivers.pop(0)
print(rivers)
rivers.append("kabani")
rivers.append("pamba")
rivers.append("bhavani")
rivers.remove("kabani")
rivers.sort()
print(rivers)
rivers.reverse()
print(rivers)
rivers.reverse()
print(rivers)
print(len(rivers))